version: '3.8'

networks:
  vita:
    driver: bridge

volumes:
  pg_data:

services:
  nginx:
    image: nginx:1.25
    ports:
      - "1243:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vita
    depends_on:
      - go_app

  go_app:
    image: golang:1.22-alpine
    environment:
      TZ: Europe/Samara
      PORT: 8080
    volumes:
      - ./:/app
    networks:
      - vita

    command: ["tail", "-f", "/dev/null"]

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: app_database
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - vita
